# Generated by Django 3.2 on 2022-01-18 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='')),
                ('post_title', models.TextField()),
                ('post_description', models.TextField(null=True)),
                ('post_date', models.DateField(default=datetime.date(2022, 1, 18))),
            ],
        ),
    ]
