# Generated by Django 3.2 on 2022-04-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_profile_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=600, null=True)),
                ('linkedin', models.CharField(max_length=600, null=True)),
                ('github', models.CharField(max_length=600, null=True)),
                ('coding', models.CharField(max_length=600, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('stream', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('marks', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
