# Generated by Django 4.0.4 on 2022-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_profile_backprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
